### ISSUE TITLE
Add extended type of "integer" for strings?

### ISSUE THREAD

**Issue by da4089** [finspec/finspec-spec#13]
In the schema, having defined the primitive data type of a field as a "string", I'd like to be able to define the extended data type as "integer" to support the specification of an ASCII string integer value (as used in the SoupBinTCP Login Request message's Requested Sequence Number field.

This isn't a bit-length extended type definition (eg int8, etc): it's a 20 character ASCII string which needs to be converted into an integer for internal processing.

I could use a regex constraint to limit the contents to numeric digits, but that doesn't reflect the semantics like an extended type of "integer" would.  Perhaps it'd be best to have both "integer" and "unsigned" too?

**Comment by mahenpatil** [comment]
This is one of the major reasons, why we kept type and format separate instead of one single type. In this case -
type : string
format : int

We have started working on version 0.2 to include most of the suggestions we have received so far, will share for the feedback once it's in decent shape. cheers!

**Comment by mahenpatil** [comment]
Included in v0.2
